# Copyright 2025 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DO NOT EDIT: generated by bazel run //src/main/kotlin/io/bazel/kotlin/generate:kotlin_release_options
TEMPLATES = [
    Label("capabilities_1.4.bzl.com_github_jetbrains_kotlin.bazel"),
    Label("capabilities_1.5.bzl.com_github_jetbrains_kotlin.bazel"),
    Label("capabilities_1.6.bzl.com_github_jetbrains_kotlin.bazel"),
    Label("capabilities_1.7.bzl.com_github_jetbrains_kotlin.bazel"),
    Label("capabilities_1.8.bzl.com_github_jetbrains_kotlin.bazel"),
    Label("capabilities_1.9.bzl.com_github_jetbrains_kotlin.bazel"),
    Label("capabilities_2.0.bzl.com_github_jetbrains_kotlin.bazel"),
    Label("capabilities_2.1.bzl.com_github_jetbrains_kotlin.bazel"),
    Label("capabilities_legacy.bzl.com_github_jetbrains_kotlin.bazel"),
]
