# Copyright 2026 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# DO NOT EDIT: generated by bazel run //src/main/kotlin/io/bazel/kotlin/generate:kotlin_release_options
TEMPLATES = [
  Label("capabilities_2.0.bzl.com_github_jetbrains_kotlin.bazel"),
  Label("capabilities_2.1.bzl.com_github_jetbrains_kotlin.bazel"),
  Label("capabilities_2.2.bzl.com_github_jetbrains_kotlin.bazel"),
  Label("capabilities_2.3.bzl.com_github_jetbrains_kotlin.bazel")
]
GENERATED_OPTS_TEMPLATES = [
  Label("generated_opts_2.0.bzl.com_github_jetbrains_kotlin.bazel"),
  Label("generated_opts_2.1.bzl.com_github_jetbrains_kotlin.bazel"),
  Label("generated_opts_2.2.bzl.com_github_jetbrains_kotlin.bazel"),
  Label("generated_opts_2.3.bzl.com_github_jetbrains_kotlin.bazel")
]