workspace(name = "multiplex")

local_repository(
    name = "io_bazel_rules_kotlin",
    path = "../../bazel-bin/rules_kotlin_release.tgz",
)

load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kotlin_repositories", "kt_register_toolchains")

kotlin_repositories()

kt_register_toolchains()
