local_repository(
    name = "release_archive",
    path = "../../src/main/starlark/release_archive",
)

load("@release_archive//:repository.bzl", "archive_repository")

archive_repository(
    name = "io_bazel_rules_kotlin",
)

load("@io_bazel_rules_kotlin//kotlin:repositories.bzl", "kotlin_repositories", "versions")

kotlin_repositories()

register_toolchains("//:kotlin_toolchain")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Skylib, for build_test, so don't bother initializing the unit test infrastructure.
http_archive(
    name = "bazel_skylib",
    sha256 = "97e70364e9249702246c0e9444bccdc4b847bed1eb03c5a3ece4f83dfe6abc44",
    urls = [
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.0.2/bazel-skylib-1.0.2.tar.gz",
    ],
)

http_archive(
    name = "rules_pkg",
    sha256 = "4ba8f4ab0ff85f2484287ab06c0d871dcb31cc54d439457d28fd4ae14b18450a",
    url = "https://github.com/bazelbuild/rules_pkg/releases/download/0.2.4/rules_pkg-0.2.4.tar.gz",
)

http_archive(
    name = "rules_jvm_external",
    sha256 = versions.RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % versions.RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % versions.RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    artifacts = [
        "com.google.dagger:dagger:2.43.2",
        "com.google.dagger:dagger-compiler:2.43.2",
        "com.google.dagger:dagger-producers:2.43.2",
        "com.squareup.anvil:compiler:2.4.1",
        "com.squareup.anvil:annotations:2.4.1",
        "androidx.activity:activity:1.0.0",
        "androidx.annotation:annotation:1.1.0",
        "androidx.appcompat:appcompat-resources:1.1.0",
        "androidx.appcompat:appcompat:1.1.0",
        "androidx.arch.core:core-common:2.1.0",
        "androidx.arch.core:core-runtime:2.0.0",
        "androidx.cardview:cardview:1.0.0",
        "androidx.collection:collection:1.1.0",
        "androidx.coordinatorlayout:coordinatorlayout:1.1.0",
        "androidx.core:core-ktx:1.3.0",
        "androidx.core:core:1.3.0",
        "androidx.cursoradapter:cursoradapter:1.0.0",
        "androidx.customview:customview:1.0.0",
        "androidx.drawerlayout:drawerlayout:1.0.0",
        "androidx.fragment:fragment:1.0.0",
        "androidx.fragment:fragment:1.1.0",
        "androidx.interpolator:interpolator:1.0.0",
        "androidx.lifecycle:lifecycle-common:2.1.0",
        "androidx.lifecycle:lifecycle-livedata-core:2.0.0",
        "androidx.lifecycle:lifecycle-livedata:2.0.0",
        "androidx.lifecycle:lifecycle-runtime:2.1.0",
        "androidx.lifecycle:lifecycle-viewmodel:2.1.0",
        "androidx.loader:loader:1.0.0",
        "androidx.recyclerview:recyclerview:1.1.0",
        "androidx.savedstate:savedstate:1.0.0",
        "androidx.transition:transition:1.2.0",
        "androidx.vectordrawable:vectordrawable-animated:1.1.0",
        "androidx.vectordrawable:vectordrawable:1.1.0",
        "androidx.versionedparcelable:versionedparcelable:1.1.0",
        "androidx.viewpager2:viewpager2:1.0.0",
        "androidx.viewpager:viewpager:1.0.0",
        "com.google.android.material:material:1.1.0",
        "javax.inject:javax.inject:1",
        "junit:junit:4.13",
        "org.jetbrains.kotlin:kotlin-test:1.5.10",
        "com.google.truth:truth:1.0.1",
        "org.jetbrains:annotations:13.0",
    ],
    excluded_artifacts = [
        "org.jetbrains.kotlin:kotlin-stdlib",
        "org.jetbrains.kotlin:kotlin-stdlib-jdk8",
        "org.jetbrains.kotlin:kotlin-stdlib-jdk7",
        "org.jetbrains.kotlin:kotlin-compiler-embeddable",
        "org.jetbrains.kotlin:kotlin-reflect",
        "org.jetbrains.kotlin:kotlin-script-runtime",
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
    use_starlark_android_rules = True,
    aar_import_bzl_label = "@io_bazel_rules_android//rules:rules.bzl",
)

http_archive(
    name = "io_bazel_rules_android",
    sha256 = versions.ANDROID.SHA,
    strip_prefix = "rules_android-%s" % versions.ANDROID.VERSION,
    urls = ["https://github.com/mauriciogg/rules_android/archive/refs/tags/pre-alpha-01-11-2022-3.zip"],
)

load("@io_bazel_rules_android//:defs.bzl", "rules_android_workspace")

rules_android_workspace()

register_toolchains(
    "@io_bazel_rules_android//toolchains/android:android_default_toolchain",
    "@io_bazel_rules_android//toolchains/android_sdk:android_sdk_tools",
)
android_sdk_repository(
    name = "androidsdk",
    build_tools_version = versions.ANDROID.BUILD_TOOLS,
)
