load("@rules_java//java:defs.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
    name = "java_deps",
    exports = [
        "@maven//:com_expedia_graphql_kotlin",
        "@maven//:com_expedia_graphql_kotlin_schema_generator",
        "@maven//:com_graphql_java_graphql_java",
        "@maven//:org_apache_logging_log4j_log4j_core",
        "@maven//:org_apiguardian_apiguardian_api",
        "@maven//:org_opentest4j_opentest4j",
    ],
)
