package(default_visibility = ["//visibility:public"])

java_library(
    name = "java_deps",
    exports = [
        "@maven//:com_expedia_graphql_kotlin",
        "@maven//:com_expedia_graphql_kotlin_schema_generator",
#        "@maven//:com_expedia_graphql_kotlin_federation",
        "@maven//:com_graphql_java_graphql_java",

        "@maven//:org_opentest4j_opentest4j",
        "@maven//:org_apiguardian_apiguardian_api",
#        "@maven//:org_junit_platform_junit_platform_commons",
#        "@maven//:org_junit_jupiter_junit_jupiter_api",
#        "@maven//:org_junit_jupiter_junit_jupiter_params",

        "@maven//:org_apache_logging_log4j_log4j_core",
    ],
)