workspace(name = "rkt_1_6")

local_repository(
    name = "release_archive",
    path = "../main/starlark/release_archive",
)

load("@release_archive//:repository.bzl", "archive_repository")

archive_repository(
    name = "dev_io_bazel_rules_kotlin",
    local_path = "../..",
)
