#!/usr/bin/env bash

# Copyright 2018 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Note: Written on a mac please make it compatible with linux if needed.

# The script precompiles the ptoto deps. If this isn't used the client workspaces would have a dependency on protoc.
# If (when) Bazel distributes a host protoc this file can be removed.

WS_ROOT=$(bazel info workspace)
PROTO_PATH=src/main/protobuf
JAR_DIR=${WS_ROOT}/${PROTO_PATH}/jars

function build_lib() {
    bazel build //${PROTO_PATH}:$1_java_proto
    local FILE=lib$1_proto-speed.jar
    cp ${WS_ROOT}/bazel-bin/${PROTO_PATH}/${FILE} ${JAR_DIR}/${FILE}
}

build_lib "deps"
build_lib "worker_protocol"
build_lib "kotlin_model"

chmod -R 0744 ${PROTO_PATH}/jars