load("@rules_java//java:defs.bzl", "java_library")

java_library(
    name = "sun_misc",
    srcs = [
        "sun/misc/Signal.java",
        "sun/misc/SignalHandler.java",
    ],
    neverlink = True,
    visibility = ["//visibility:public"],
)