# Copyright 2018 The Bazel Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
load("//kotlin/internal/utils:packager.bzl", "release_archive")
load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

release_archive(
    name = "pkg",
    srcs = [
        "BUILD.com_github_jetbrains_kotlin",
        "download.bzl",
        "tools.bzl",
    ],
    src_map = {
        "release_repositories.bzl": "repositories.bzl",
        "BUILD.release.bazel": "BUILD.bazel",
    },
)

bzl_library(
    name = "repositories",
    srcs = glob(["*.bzl"]),
    visibility = ["//kotlin:__subpackages__"],
)
