load("@rules_kotlin//kotlin:core.bzl", "define_kt_toolchain")

define_kt_toolchain(
    name = "kotlin_toolchain",
    api_version = "2.1",
    experimental_generate_associates_abi_jars = True,
    experimental_remove_private_classes_in_abi_jars = True,
    experimental_treat_internal_as_private_in_abi_jars = True,
    experimental_use_abi_jars = True,
    language_version = "2.1",
)
